version: "3.4"

services:
  gametts:
    image: henrikhansen/gametts:latest
    expose:
     - 5000
    restart: always

  # jack:
  #   build: 
  #     context: jack
  #   volumes:
  #       - "/dev/shm:/dev/shm:rw"
  #   privileged: true
  #   shm_size: 256m
  #   cap_add:
  #      - sys_nice
  #   restart: always
  #   ulimits:
  #     rtprio: 95
  #     memlock: -1

  mixer:
    build:
      context: mixer
    restart: always
    ports:
      - 5900:5900/tcp
      - 5901:5901/tcp
      - 7890:7890/tcp
      - 7890:7890/udp
    volumes:
        - "/dev/shm:/dev/shm:rw"
    # depends_on:
    #   - jack
    privileged: true
    shm_size: 256m
    cap_add:
       - sys_nice
    ulimits:
      rtprio: 95
      memlock: -1

  autojack:
    build: 
      context: autojack
    volumes:
        - "./aj-settings.conf:/root/aj-settings.conf"
        - "/dev/shm:/dev/shm:rw"
    depends_on:
      - mixer

  radio:
    build: 
      context: radio
    environment:
      - RADIO_URL=https://player.ffn.de/radioffn.mp3
    volumes:
        - "/dev/shm:/dev/shm:rw"
    privileged: true
    depends_on:
      - mixer
      - autojack

  database-bootstrap:
     build: 
       context: database-bootstrap
     environment:
      - SQLFILE=dump.sql
      - MYSQL_ROOT_PASSWORD=changeme
     depends_on:
     - database

  database:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_USER=durchsagen
      - MYSQL_PASSWORD=durchsagen
      - MYSQL_DATABASE=durchsagen
    expose:
      - 3306
    volumes:
      - /tmp/mysql:/var/lib/mysql
    restart: always
       
  asterisk:
    image: hhansen06/campsite-asterisk
    ports:
      - 5060:5060/udp                     # SIP UDP port
      - 5060:5060                         # SIP TCP port
      - 5061:5061                         # SIP TLS port
      - 10000-10099:10000-10099/udp        # RTP ports
    volumes:
      - ./durchsagen:/durchsagen
    build: 
      context: asterisk
      dockerfile: Dockerfile
    environment: 
      - SERVER_IP=172.18.12.7
      - SIP_REGISTER=zeltlagerkram:asdqwe123@172.18.5.2
      - SIP_SERVER=172.18.5.2
      - SIP_USER=zeltlagerkram
      - SIP_PASSWD=asdqwe123 
      - SIP_LOCALNET=172.18.12.0/255.255.255.0
      - MYSQL_USER=durchsagen
      - MYSQL_PASSWORD=durchsagen
      - MYSQL_DATABASE=durchsagen
      - VOICE_ID=73

  # icecast:
  #   image: deepcomp/icecast2
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - ICECAST_SOURCE_PASSWORD=hackme
  #     - ICECAST_ADMIN_USER=admin
  #     - ICECAST_ADMIN_PASSWORD=changeme
  #     - TZ=Europe/Berlin
  
  # streamer:
  #   build: 
  #     context: streamer
  #   volumes:
  #       - "/dev/shm:/dev/shm:rw"
  #   privileged: true
  #   depends_on:
  #     - jack
  #     - mixer
  #     - autojack