version: "3.4"
services:
  asterisk:
     image: hhansen06/campsite-asterisk
     build: 
       context: asterisk
       dockerfile: Dockerfile
     environment: 
       - SIP_SERVER=172.18.5.2
       - SIP_USER=zeltlagerkram
       - SIP_PASSWD=asdqwe123 
    

#  webserver:
#    image: ghcr.io/paperless-ngx/paperless-ngx:latest
#    restart: always
#    depends_on:
#      - db
#      - broker
#    ports:
#      - 80:8000
#    healthcheck:
#      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
#      interval: 30s
#      timeout: 10s
#      retries: 5
#    volumes:
#      - ./data:/usr/src/paperless/data
##      - ./media:/usr/src/paperless/media
 #     - ./export:/usr/src/paperless/export
 #     - ./consume:/usr/src/paperless/consume