version: "3.4"
services:
  database-bootstrap:
     build: 
       context: database-bootstrap
     environment:
      - SQLFILE=dump.sql
      - MYSQL_ROOT_PASSWORD=changeme
     links:
     - database

  database:
     image: mysql:latest
     environment:
       - MYSQL_ROOT_PASSWORD=changeme
       - MYSQL_USER=durchsagen
       - MYSQL_PASSWORD=durchsagen
       - MYSQL_DATABASE=durchsagen
     expose:
       - 3306
     volumes:
       - /tmp/mysql:/var/lib/mysql
       
  asterisk:
     image: hhansen06/campsite-asterisk
     network_mode: host
     build: 
       context: asterisk
       dockerfile: Dockerfile
     environment: 
       - SIP_REGISTER=zeltlagerkram:asdqwe123@172.18.5.2
       - SIP_SERVER=172.18.5.2
       - SIP_USER=zeltlagerkram
       - SIP_PASSWD=asdqwe123 
       - SIP_LOCALNET=172.18.12.0/255.255.255.0
     

#  webserver:
#    image: ghcr.io/paperless-ngx/paperless-ngx:latest
#    restart: always
#    depends_on:
#      - db
#      - broker
#    ports:
#      - 80:8000
#    healthcheck:
#      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
#      interval: 30s
#      timeout: 10s
#      retries: 5
#    volumes:
#      - ./data:/usr/src/paperless/data
##      - ./media:/usr/src/paperless/media
 #     - ./export:/usr/src/paperless/export
 #     - ./consume:/usr/src/paperless/consume